apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/network-tier: Standard
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: "35.209.21.126"
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
